doc-warnings: false
test-warnings: false
strictness: medium
autodetect: true
ignore-paths:
  - config
  - docs
  - tests
ignore-patterns:
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
python-targets:
  - 3
