language: python

python:
  - "3.5"

install:
  - pip install numpy
  - pip install -r requirements.txt

script:
  - python -m unittest discover tests/
  - codecov

after_success:
  - 'bash < (curl -s https://codecov.io/bash)'