sudo: false

language: python

python:
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest -v --cov=generalization

after_success:
   - pipenv run codecov
#  - 'bash < (curl -s https://codecov.io/bash)'