sudo: false

language: python

python:
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest -v --cov=generalization
#  - coverage run tests/test_all.py
#  - python -m unittest discover tests/

after_success:
   - pipenv run codecov
#  - 'bash < (curl -s https://codecov.io/bash)'