sudo: false

language: python

python:
  - "3.5"

install:
  - pip install numpy
  - pip install -r requirements.txt

script:
  - pytest -v --cov=generalization
#  - coverage run tests/test_all.py
#  - python -m unittest discover tests/

after_success:
   - codecov
#  - 'bash < (curl -s https://codecov.io/bash)'