site_name: ML-generalization

pages:
    - Home: index.rst
    - Installation: installation.rst
    - Running the tests: tests.rst
    - Usage: usage.rst
    - Uninstallation: uninstallation.rst

theme: readthedocs